import Head from 'next/head';
import styles from '../styles/Home.module.css';
import AbaMenu from '../src/componentes/AbaMenu';
import { useState } from 'react';
import Rodape from '../src/componentes/Rodape';


export default function Home() {
  const [ativaAbaMenu,setAtivaAbaMenu] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Renee Trajar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/LogoIcon.svg" />
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&family=Playfair+Display&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&family=Playfair+Display&family=Poppins:wght@300&display=swap" rel="stylesheet"/>
      </Head>

      <header className={styles.header}>
        <button className={styles.iconeMenu} onClick={()=>setAtivaAbaMenu(!ativaAbaMenu)}><img  src="/images/Menu.svg"/></button>
        <img className={styles.logoInicial}src="/images/Logo.svg"/>
      </header>
      <AbaMenu estadoAba={ativaAbaMenu} acaoAba={setAtivaAbaMenu}/>  
      <main className={styles.main}>
        <h1 className={styles.titulo}>
          Elegante é ter um <br/>
          <span className={styles.tituloSpan}>alfaiate</span></h1>
        <p className={styles.tituloFinal}> para chamar de seu. </p>
        <h2 className={styles.chamada}>Compre hoje, pague em até 3x com 12% de desconto e tenha 10 meses para confeccionar!</h2>
        <button className={styles.wtspLink}><img src='/images/wtsp.svg'/></button>
        <button className={styles.botaoDeChamada}>Faça já um orçamento</button>
        

       {/*  <p className={styles.description}>
        Com mais de 35 anos de experiência{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>
      <Rodape/>

    </div>
  )
}
